# this playbook yaml is for variables
- name: variables in ansible
  hosts: mongodb
  vars:
    COURSE: DEVOPS
    TRAINER: SIVAKUMAR
    HOURS: 100
  tasks:
  - name: printing hello world
    ansible.builtin.debug:
    msg: "hello world, Im learning devops with aws"
  - name: printing variables
    ansible.builtin.debug:
    msg: "Iam learning {{COURSE}},Training by {{TRAINER}},with duration of {{HOURS}} hours."